# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cloudquery/discovery_v1/discovery.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'cloudquery/discovery_v1/discovery.proto\x12\x17\x63loudquery.discovery.v1\"6\n\x0bGetVersions\x1a\t\n\x07Request\x1a\x1c\n\x08Response\x12\x10\n\x08versions\x18\x01 \x03(\x05\x32w\n\tDiscovery\x12j\n\x0bGetVersions\x12,.cloudquery.discovery.v1.GetVersions.Request\x1a-.cloudquery.discovery.v1.GetVersions.ResponseB\\\n\x1aio.cloudquery.discovery.v1P\x01Z<github.com/cloudquery/plugin-pb-go/pb/discovery/v1;discoveryb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cloudquery.discovery_v1.discovery_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\032io.cloudquery.discovery.v1P\001Z<github.com/cloudquery/plugin-pb-go/pb/discovery/v1;discovery'
  _globals['_GETVERSIONS']._serialized_start=68
  _globals['_GETVERSIONS']._serialized_end=122
  _globals['_GETVERSIONS_REQUEST']._serialized_start=83
  _globals['_GETVERSIONS_REQUEST']._serialized_end=92
  _globals['_GETVERSIONS_RESPONSE']._serialized_start=94
  _globals['_GETVERSIONS_RESPONSE']._serialized_end=122
  _globals['_DISCOVERY']._serialized_start=124
  _globals['_DISCOVERY']._serialized_end=243
# @@protoc_insertion_point(module_scope)
